/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileStorage */

#ifndef _Included_com_example_testreadxmlfile_FileStorage
#define _Included_com_example_testreadxmlfile_FileStorage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileStorage
 * Method:    CalcFeatures
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_testreadxmlfile_FileStorage_nativeCalcFeatures
  (JNIEnv *, jclass, jstring);
/*
 * Class:     FileStorage
 * Method:    nativeSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testreadxmlfile_FileStorage_nativeSayHello
  (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
